### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [AkshayPatil347/Grover-s-Code#1]
I recently came across your project Grover-s-Code and I noticed that the repository github.com/AkshayPatil347/Grover-s-Code currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by AkshayPatil347** [comment]
Hi Mr.Juan , sure ! Please Kindly walk through the procedure of licensing
this repo , but since it is added to my github repo .. it is unofficially
an open source and people are free to use and distribute it (that is what i
thought)... thanks for bringing this to my notice Mr.Juan ...

**Comment by cbjuan** [comment]
Thanks!
